Set m2e = CreateObject("Scripting.Dictionary")
m2e.Add "application/andrew-inset", Split("ez", " ")
m2e.Add "application/applixware", Split("aw", " ")
m2e.Add "application/atom+xml", Split("atom", " ")
m2e.Add "application/atomcat+xml", Split("atomcat", " ")
m2e.Add "application/atomsvc+xml", Split("atomsvc", " ")
m2e.Add "application/ccxml+xml", Split("ccxml", " ")
m2e.Add "application/cdmi-capability", Split("cdmia", " ")
m2e.Add "application/cdmi-container", Split("cdmic", " ")
m2e.Add "application/cdmi-domain", Split("cdmid", " ")
m2e.Add "application/cdmi-object", Split("cdmio", " ")
m2e.Add "application/cdmi-queue", Split("cdmiq", " ")
m2e.Add "application/cu-seeme", Split("cu", " ")
m2e.Add "application/davmount+xml", Split("davmount", " ")
m2e.Add "application/docbook+xml", Split("dbk", " ")
m2e.Add "application/dssc+der", Split("dssc", " ")
m2e.Add "application/dssc+xml", Split("xdssc", " ")
m2e.Add "application/ecmascript", Split("ecma", " ")
m2e.Add "application/emma+xml", Split("emma", " ")
m2e.Add "application/epub+zip", Split("epub", " ")
m2e.Add "application/exi", Split("exi", " ")
m2e.Add "application/font-tdpfr", Split("pfr", " ")
m2e.Add "application/gml+xml", Split("gml", " ")
m2e.Add "application/gpx+xml", Split("gpx", " ")
m2e.Add "application/gxf", Split("gxf", " ")
m2e.Add "application/hyperstudio", Split("stk", " ")
m2e.Add "application/inkml+xml", Split("ink inkml", " ")
m2e.Add "application/ipfix", Split("ipfix", " ")
m2e.Add "application/java-archive", Split("jar", " ")
m2e.Add "application/java-serialized-object", Split("ser", " ")
m2e.Add "application/java-vm", Split("class", " ")
m2e.Add "application/javascript", Split("js", " ")
m2e.Add "application/json", Split("json", " ")
m2e.Add "application/jsonml+json", Split("jsonml", " ")
m2e.Add "application/lost+xml", Split("lostxml", " ")
m2e.Add "application/mac-binhex40", Split("hqx", " ")
m2e.Add "application/mac-compactpro", Split("cpt", " ")
m2e.Add "application/mads+xml", Split("mads", " ")
m2e.Add "application/marc", Split("mrc", " ")
m2e.Add "application/marcxml+xml", Split("mrcx", " ")
m2e.Add "application/mathematica", Split("ma nb mb", " ")
m2e.Add "application/mathml+xml", Split("mathml", " ")
m2e.Add "application/mbox", Split("mbox", " ")
m2e.Add "application/mediaservercontrol+xml", Split("mscml", " ")
m2e.Add "application/metalink+xml", Split("metalink", " ")
m2e.Add "application/metalink4+xml", Split("meta4", " ")
m2e.Add "application/mets+xml", Split("mets", " ")
m2e.Add "application/mods+xml", Split("mods", " ")
m2e.Add "application/mp21", Split("m21 mp21", " ")
m2e.Add "application/mp4", Split("mp4s", " ")
m2e.Add "application/msword", Split("doc dot", " ")
m2e.Add "application/mxf", Split("mxf", " ")
m2e.Add "application/octet-stream", Split("bin dms lrf mar so dist distz pkg bpk dump elc deploy", " ")
m2e.Add "application/oda", Split("oda", " ")
m2e.Add "application/oebps-package+xml", Split("opf", " ")
m2e.Add "application/ogg", Split("ogx", " ")
m2e.Add "application/omdoc+xml", Split("omdoc", " ")
m2e.Add "application/onenote", Split("onetoc onetoc2 onetmp onepkg", " ")
m2e.Add "application/oxps", Split("oxps", " ")
m2e.Add "application/patch-ops-error+xml", Split("xer", " ")
m2e.Add "application/pdf", Split("pdf", " ")
m2e.Add "application/pgp-encrypted", Split("pgp", " ")
m2e.Add "application/pgp-signature", Split("asc sig", " ")
m2e.Add "application/pics-rules", Split("prf", " ")
m2e.Add "application/pkcs10", Split("p10", " ")
m2e.Add "application/pkcs7-mime", Split("p7m p7c", " ")
m2e.Add "application/pkcs7-signature", Split("p7s", " ")
m2e.Add "application/pkcs8", Split("p8", " ")
m2e.Add "application/pkix-attr-cert", Split("ac", " ")
m2e.Add "application/pkix-cert", Split("cer", " ")
m2e.Add "application/pkix-crl", Split("crl", " ")
m2e.Add "application/pkix-pkipath", Split("pkipath", " ")
m2e.Add "application/pkixcmp", Split("pki", " ")
m2e.Add "application/pls+xml", Split("pls", " ")
m2e.Add "application/postscript", Split("ai eps ps", " ")
m2e.Add "application/prs.cww", Split("cww", " ")
m2e.Add "application/pskc+xml", Split("pskcxml", " ")
m2e.Add "application/rdf+xml", Split("rdf", " ")
m2e.Add "application/reginfo+xml", Split("rif", " ")
m2e.Add "application/relax-ng-compact-syntax", Split("rnc", " ")
m2e.Add "application/resource-lists+xml", Split("rl", " ")
m2e.Add "application/resource-lists-diff+xml", Split("rld", " ")
m2e.Add "application/rls-services+xml", Split("rs", " ")
m2e.Add "application/rpki-ghostbusters", Split("gbr", " ")
m2e.Add "application/rpki-manifest", Split("mft", " ")
m2e.Add "application/rpki-roa", Split("roa", " ")
m2e.Add "application/rsd+xml", Split("rsd", " ")
m2e.Add "application/rss+xml", Split("rss", " ")
m2e.Add "application/rtf", Split("rtf", " ")
m2e.Add "application/sbml+xml", Split("sbml", " ")
m2e.Add "application/scvp-cv-request", Split("scq", " ")
m2e.Add "application/scvp-cv-response", Split("scs", " ")
m2e.Add "application/scvp-vp-request", Split("spq", " ")
m2e.Add "application/scvp-vp-response", Split("spp", " ")
m2e.Add "application/sdp", Split("sdp", " ")
m2e.Add "application/set-payment-initiation", Split("setpay", " ")
m2e.Add "application/set-registration-initiation", Split("setreg", " ")
m2e.Add "application/shf+xml", Split("shf", " ")
m2e.Add "application/smil+xml", Split("smi smil", " ")
m2e.Add "application/sparql-query", Split("rq", " ")
m2e.Add "application/sparql-results+xml", Split("srx", " ")
m2e.Add "application/srgs", Split("gram", " ")
m2e.Add "application/srgs+xml", Split("grxml", " ")
m2e.Add "application/sru+xml", Split("sru", " ")
m2e.Add "application/ssdl+xml", Split("ssdl", " ")
m2e.Add "application/ssml+xml", Split("ssml", " ")
m2e.Add "application/tei+xml", Split("tei teicorpus", " ")
m2e.Add "application/thraud+xml", Split("tfi", " ")
m2e.Add "application/timestamped-data", Split("tsd", " ")
m2e.Add "application/vnd.3gpp.pic-bw-large", Split("plb", " ")
m2e.Add "application/vnd.3gpp.pic-bw-small", Split("psb", " ")
m2e.Add "application/vnd.3gpp.pic-bw-var", Split("pvb", " ")
m2e.Add "application/vnd.3gpp2.tcap", Split("tcap", " ")
m2e.Add "application/vnd.3m.post-it-notes", Split("pwn", " ")
m2e.Add "application/vnd.accpac.simply.aso", Split("aso", " ")
m2e.Add "application/vnd.accpac.simply.imp", Split("imp", " ")
m2e.Add "application/vnd.acucobol", Split("acu", " ")
m2e.Add "application/vnd.acucorp", Split("atc acutc", " ")
m2e.Add "application/vnd.adobe.air-application-installer-package+zip", Split("air", " ")
m2e.Add "application/vnd.adobe.formscentral.fcdt", Split("fcdt", " ")
m2e.Add "application/vnd.adobe.fxp", Split("fxp fxpl", " ")
m2e.Add "application/vnd.adobe.xdp+xml", Split("xdp", " ")
m2e.Add "application/vnd.adobe.xfdf", Split("xfdf", " ")
m2e.Add "application/vnd.ahead.space", Split("ahead", " ")
m2e.Add "application/vnd.airzip.filesecure.azf", Split("azf", " ")
m2e.Add "application/vnd.airzip.filesecure.azs", Split("azs", " ")
m2e.Add "application/vnd.amazon.ebook", Split("azw", " ")
m2e.Add "application/vnd.americandynamics.acc", Split("acc", " ")
m2e.Add "application/vnd.amiga.ami", Split("ami", " ")
m2e.Add "application/vnd.android.package-archive", Split("apk", " ")
m2e.Add "application/vnd.anser-web-certificate-issue-initiation", Split("cii", " ")
m2e.Add "application/vnd.anser-web-funds-transfer-initiation", Split("fti", " ")
m2e.Add "application/vnd.antix.game-component", Split("atx", " ")
m2e.Add "application/vnd.apple.installer+xml", Split("mpkg", " ")
m2e.Add "application/vnd.apple.mpegurl", Split("m3u8", " ")
m2e.Add "application/vnd.aristanetworks.swi", Split("swi", " ")
m2e.Add "application/vnd.astraea-software.iota", Split("iota", " ")
m2e.Add "application/vnd.audiograph", Split("aep", " ")
m2e.Add "application/vnd.blueice.multipass", Split("mpm", " ")
m2e.Add "application/vnd.bmi", Split("bmi", " ")
m2e.Add "application/vnd.businessobjects", Split("rep", " ")
m2e.Add "application/vnd.chemdraw+xml", Split("cdxml", " ")
m2e.Add "application/vnd.chipnuts.karaoke-mmd", Split("mmd", " ")
m2e.Add "application/vnd.cinderella", Split("cdy", " ")
m2e.Add "application/vnd.claymore", Split("cla", " ")
m2e.Add "application/vnd.cloanto.rp9", Split("rp9", " ")
m2e.Add "application/vnd.clonk.c4group", Split("c4g c4d c4f c4p c4u", " ")
m2e.Add "application/vnd.cluetrust.cartomobile-config", Split("c11amc", " ")
m2e.Add "application/vnd.cluetrust.cartomobile-config-pkg", Split("c11amz", " ")
m2e.Add "application/vnd.commonspace", Split("csp", " ")
m2e.Add "application/vnd.contact.cmsg", Split("cdbcmsg", " ")
m2e.Add "application/vnd.cosmocaller", Split("cmc", " ")
m2e.Add "application/vnd.crick.clicker", Split("clkx", " ")
m2e.Add "application/vnd.crick.clicker.keyboard", Split("clkk", " ")
m2e.Add "application/vnd.crick.clicker.palette", Split("clkp", " ")
m2e.Add "application/vnd.crick.clicker.template", Split("clkt", " ")
m2e.Add "application/vnd.crick.clicker.wordbank", Split("clkw", " ")
m2e.Add "application/vnd.criticaltools.wbs+xml", Split("wbs", " ")
m2e.Add "application/vnd.ctc-posml", Split("pml", " ")
m2e.Add "application/vnd.cups-ppd", Split("ppd", " ")
m2e.Add "application/vnd.curl.car", Split("car", " ")
m2e.Add "application/vnd.curl.pcurl", Split("pcurl", " ")
m2e.Add "application/vnd.dart", Split("dart", " ")
m2e.Add "application/vnd.data-vision.rdz", Split("rdz", " ")
m2e.Add "application/vnd.dece.data", Split("uvf uvvf uvd uvvd", " ")
m2e.Add "application/vnd.dece.ttml+xml", Split("uvt uvvt", " ")
m2e.Add "application/vnd.dece.unspecified", Split("uvx uvvx", " ")
m2e.Add "application/vnd.dece.zip", Split("uvz uvvz", " ")
m2e.Add "application/vnd.denovo.fcselayout-link", Split("fe_launch", " ")
m2e.Add "application/vnd.dna", Split("dna", " ")
m2e.Add "application/vnd.dolby.mlp", Split("mlp", " ")
m2e.Add "application/vnd.dpgraph", Split("dpg", " ")
m2e.Add "application/vnd.dreamfactory", Split("dfac", " ")
m2e.Add "application/vnd.ds-keypoint", Split("kpxx", " ")
m2e.Add "application/vnd.dvb.ait", Split("ait", " ")
m2e.Add "application/vnd.dvb.service", Split("svc", " ")
m2e.Add "application/vnd.dynageo", Split("geo", " ")
m2e.Add "application/vnd.ecowin.chart", Split("mag", " ")
m2e.Add "application/vnd.enliven", Split("nml", " ")
m2e.Add "application/vnd.epson.esf", Split("esf", " ")
m2e.Add "application/vnd.epson.msf", Split("msf", " ")
m2e.Add "application/vnd.epson.quickanime", Split("qam", " ")
m2e.Add "application/vnd.epson.salt", Split("slt", " ")
m2e.Add "application/vnd.epson.ssf", Split("ssf", " ")
m2e.Add "application/vnd.eszigno3+xml", Split("es3 et3", " ")
m2e.Add "application/vnd.ezpix-album", Split("ez2", " ")
m2e.Add "application/vnd.ezpix-package", Split("ez3", " ")
m2e.Add "application/vnd.fdf", Split("fdf", " ")
m2e.Add "application/vnd.fdsn.mseed", Split("mseed", " ")
m2e.Add "application/vnd.fdsn.seed", Split("seed dataless", " ")
m2e.Add "application/vnd.flographit", Split("gph", " ")
m2e.Add "application/vnd.fluxtime.clip", Split("ftc", " ")
m2e.Add "application/vnd.framemaker", Split("fm frame maker book", " ")
m2e.Add "application/vnd.frogans.fnc", Split("fnc", " ")
m2e.Add "application/vnd.frogans.ltf", Split("ltf", " ")
m2e.Add "application/vnd.fsc.weblaunch", Split("fsc", " ")
m2e.Add "application/vnd.fujitsu.oasys", Split("oas", " ")
m2e.Add "application/vnd.fujitsu.oasys2", Split("oa2", " ")
m2e.Add "application/vnd.fujitsu.oasys3", Split("oa3", " ")
m2e.Add "application/vnd.fujitsu.oasysgp", Split("fg5", " ")
m2e.Add "application/vnd.fujitsu.oasysprs", Split("bh2", " ")
m2e.Add "application/vnd.fujixerox.ddd", Split("ddd", " ")
m2e.Add "application/vnd.fujixerox.docuworks", Split("xdw", " ")
m2e.Add "application/vnd.fujixerox.docuworks.binder", Split("xbd", " ")
m2e.Add "application/vnd.fuzzysheet", Split("fzs", " ")
m2e.Add "application/vnd.genomatix.tuxedo", Split("txd", " ")
m2e.Add "application/vnd.geogebra.file", Split("ggb", " ")
m2e.Add "application/vnd.geogebra.tool", Split("ggt", " ")
m2e.Add "application/vnd.geometry-explorer", Split("gex gre", " ")
m2e.Add "application/vnd.geonext", Split("gxt", " ")
m2e.Add "application/vnd.geoplan", Split("g2w", " ")
m2e.Add "application/vnd.geospace", Split("g3w", " ")
m2e.Add "application/vnd.gmx", Split("gmx", " ")
m2e.Add "application/vnd.google-earth.kml+xml", Split("kml", " ")
m2e.Add "application/vnd.google-earth.kmz", Split("kmz", " ")
m2e.Add "application/vnd.grafeq", Split("gqf gqs", " ")
m2e.Add "application/vnd.groove-account", Split("gac", " ")
m2e.Add "application/vnd.groove-help", Split("ghf", " ")
m2e.Add "application/vnd.groove-identity-message", Split("gim", " ")
m2e.Add "application/vnd.groove-injector", Split("grv", " ")
m2e.Add "application/vnd.groove-tool-message", Split("gtm", " ")
m2e.Add "application/vnd.groove-tool-template", Split("tpl", " ")
m2e.Add "application/vnd.groove-vcard", Split("vcg", " ")
m2e.Add "application/vnd.hal+xml", Split("hal", " ")
m2e.Add "application/vnd.handheld-entertainment+xml", Split("zmm", " ")
m2e.Add "application/vnd.hbci", Split("hbci", " ")
m2e.Add "application/vnd.hhe.lesson-player", Split("les", " ")
m2e.Add "application/vnd.hp-hpgl", Split("hpgl", " ")
m2e.Add "application/vnd.hp-hpid", Split("hpid", " ")
m2e.Add "application/vnd.hp-hps", Split("hps", " ")
m2e.Add "application/vnd.hp-jlyt", Split("jlt", " ")
m2e.Add "application/vnd.hp-pcl", Split("pcl", " ")
m2e.Add "application/vnd.hp-pclxl", Split("pclxl", " ")
m2e.Add "application/vnd.hydrostatix.sof-data", Split("sfd-hdstx", " ")
m2e.Add "application/vnd.ibm.minipay", Split("mpy", " ")
m2e.Add "application/vnd.ibm.modcap", Split("afp listafp list3820", " ")
m2e.Add "application/vnd.ibm.rights-management", Split("irm", " ")
m2e.Add "application/vnd.ibm.secure-container", Split("sc", " ")
m2e.Add "application/vnd.iccprofile", Split("icc icm", " ")
m2e.Add "application/vnd.igloader", Split("igl", " ")
m2e.Add "application/vnd.immervision-ivp", Split("ivp", " ")
m2e.Add "application/vnd.immervision-ivu", Split("ivu", " ")
m2e.Add "application/vnd.insors.igm", Split("igm", " ")
m2e.Add "application/vnd.intercon.formnet", Split("xpw xpx", " ")
m2e.Add "application/vnd.intergeo", Split("i2g", " ")
m2e.Add "application/vnd.intu.qbo", Split("qbo", " ")
m2e.Add "application/vnd.intu.qfx", Split("qfx", " ")
m2e.Add "application/vnd.ipunplugged.rcprofile", Split("rcprofile", " ")
m2e.Add "application/vnd.irepository.package+xml", Split("irp", " ")
m2e.Add "application/vnd.is-xpr", Split("xpr", " ")
m2e.Add "application/vnd.isac.fcs", Split("fcs", " ")
m2e.Add "application/vnd.jam", Split("jam", " ")
m2e.Add "application/vnd.jcp.javame.midlet-rms", Split("rms", " ")
m2e.Add "application/vnd.jisp", Split("jisp", " ")
m2e.Add "application/vnd.joost.joda-archive", Split("joda", " ")
m2e.Add "application/vnd.kahootz", Split("ktz ktr", " ")
m2e.Add "application/vnd.kde.karbon", Split("karbon", " ")
m2e.Add "application/vnd.kde.kchart", Split("chrt", " ")
m2e.Add "application/vnd.kde.kformula", Split("kfo", " ")
m2e.Add "application/vnd.kde.kivio", Split("flw", " ")
m2e.Add "application/vnd.kde.kontour", Split("kon", " ")
m2e.Add "application/vnd.kde.kpresenter", Split("kpr kpt", " ")
m2e.Add "application/vnd.kde.kspread", Split("ksp", " ")
m2e.Add "application/vnd.kde.kword", Split("kwd kwt", " ")
m2e.Add "application/vnd.kenameaapp", Split("htke", " ")
m2e.Add "application/vnd.kidspiration", Split("kia", " ")
m2e.Add "application/vnd.kinar", Split("kne knp", " ")
m2e.Add "application/vnd.koan", Split("skp skd skt skm", " ")
m2e.Add "application/vnd.kodak-descriptor", Split("sse", " ")
m2e.Add "application/vnd.las.las+xml", Split("lasxml", " ")
m2e.Add "application/vnd.llamagraphics.life-balance.desktop", Split("lbd", " ")
m2e.Add "application/vnd.llamagraphics.life-balance.exchange+xml", Split("lbe", " ")
m2e.Add "application/vnd.lotus-1-2-3", Split("123", " ")
m2e.Add "application/vnd.lotus-approach", Split("apr", " ")
m2e.Add "application/vnd.lotus-freelance", Split("pre", " ")
m2e.Add "application/vnd.lotus-notes", Split("nsf", " ")
m2e.Add "application/vnd.lotus-organizer", Split("org", " ")
m2e.Add "application/vnd.lotus-screencam", Split("scm", " ")
m2e.Add "application/vnd.lotus-wordpro", Split("lwp", " ")
m2e.Add "application/vnd.macports.portpkg", Split("portpkg", " ")
m2e.Add "application/vnd.mcd", Split("mcd", " ")
m2e.Add "application/vnd.medcalcdata", Split("mc1", " ")
m2e.Add "application/vnd.mediastation.cdkey", Split("cdkey", " ")
m2e.Add "application/vnd.mfer", Split("mwf", " ")
m2e.Add "application/vnd.mfmp", Split("mfm", " ")
m2e.Add "application/vnd.micrografx.flo", Split("flo", " ")
m2e.Add "application/vnd.micrografx.igx", Split("igx", " ")
m2e.Add "application/vnd.mif", Split("mif", " ")
m2e.Add "application/vnd.mobius.daf", Split("daf", " ")
m2e.Add "application/vnd.mobius.dis", Split("dis", " ")
m2e.Add "application/vnd.mobius.mbk", Split("mbk", " ")
m2e.Add "application/vnd.mobius.mqy", Split("mqy", " ")
m2e.Add "application/vnd.mobius.msl", Split("msl", " ")
m2e.Add "application/vnd.mobius.plc", Split("plc", " ")
m2e.Add "application/vnd.mobius.txf", Split("txf", " ")
m2e.Add "application/vnd.mophun.application", Split("mpn", " ")
m2e.Add "application/vnd.mophun.certificate", Split("mpc", " ")
m2e.Add "application/vnd.mozilla.xul+xml", Split("xul", " ")
m2e.Add "application/vnd.ms-artgalry", Split("cil", " ")
m2e.Add "application/vnd.ms-cab-compressed", Split("cab", " ")
m2e.Add "application/vnd.ms-excel", Split("xls xlm xla xlc xlt xlw", " ")
m2e.Add "application/vnd.ms-excel.addin.macroenabled.12", Split("xlam", " ")
m2e.Add "application/vnd.ms-excel.sheet.binary.macroenabled.12", Split("xlsb", " ")
m2e.Add "application/vnd.ms-excel.sheet.macroenabled.12", Split("xlsm", " ")
m2e.Add "application/vnd.ms-excel.template.macroenabled.12", Split("xltm", " ")
m2e.Add "application/vnd.ms-fontobject", Split("eot", " ")
m2e.Add "application/vnd.ms-htmlhelp", Split("chm", " ")
m2e.Add "application/vnd.ms-ims", Split("ims", " ")
m2e.Add "application/vnd.ms-lrm", Split("lrm", " ")
m2e.Add "application/vnd.ms-officetheme", Split("thmx", " ")
m2e.Add "application/vnd.ms-pki.seccat", Split("cat", " ")
m2e.Add "application/vnd.ms-pki.stl", Split("stl", " ")
m2e.Add "application/vnd.ms-powerpoint", Split("ppt pps pot", " ")
m2e.Add "application/vnd.ms-powerpoint.addin.macroenabled.12", Split("ppam", " ")
m2e.Add "application/vnd.ms-powerpoint.presentation.macroenabled.12", Split("pptm", " ")
m2e.Add "application/vnd.ms-powerpoint.slide.macroenabled.12", Split("sldm", " ")
m2e.Add "application/vnd.ms-powerpoint.slideshow.macroenabled.12", Split("ppsm", " ")
m2e.Add "application/vnd.ms-powerpoint.template.macroenabled.12", Split("potm", " ")
m2e.Add "application/vnd.ms-project", Split("mpp mpt", " ")
m2e.Add "application/vnd.ms-word.document.macroenabled.12", Split("docm", " ")
m2e.Add "application/vnd.ms-word.template.macroenabled.12", Split("dotm", " ")
m2e.Add "application/vnd.ms-works", Split("wps wks wcm wdb", " ")
m2e.Add "application/vnd.ms-wpl", Split("wpl", " ")
m2e.Add "application/vnd.ms-xpsdocument", Split("xps", " ")
m2e.Add "application/vnd.mseq", Split("mseq", " ")
m2e.Add "application/vnd.musician", Split("mus", " ")
m2e.Add "application/vnd.muvee.style", Split("msty", " ")
m2e.Add "application/vnd.mynfc", Split("taglet", " ")
m2e.Add "application/vnd.neurolanguage.nlu", Split("nlu", " ")
m2e.Add "application/vnd.nitf", Split("ntf nitf", " ")
m2e.Add "application/vnd.noblenet-directory", Split("nnd", " ")
m2e.Add "application/vnd.noblenet-sealer", Split("nns", " ")
m2e.Add "application/vnd.noblenet-web", Split("nnw", " ")
m2e.Add "application/vnd.nokia.n-gage.data", Split("ngdat", " ")
m2e.Add "application/vnd.nokia.n-gage.symbian.install", Split("n-gage", " ")
m2e.Add "application/vnd.nokia.radio-preset", Split("rpst", " ")
m2e.Add "application/vnd.nokia.radio-presets", Split("rpss", " ")
m2e.Add "application/vnd.novadigm.edm", Split("edm", " ")
m2e.Add "application/vnd.novadigm.edx", Split("edx", " ")
m2e.Add "application/vnd.novadigm.ext", Split("ext", " ")
m2e.Add "application/vnd.oasis.opendocument.chart", Split("odc", " ")
m2e.Add "application/vnd.oasis.opendocument.chart-template", Split("otc", " ")
m2e.Add "application/vnd.oasis.opendocument.database", Split("odb", " ")
m2e.Add "application/vnd.oasis.opendocument.formula", Split("odf", " ")
m2e.Add "application/vnd.oasis.opendocument.formula-template", Split("odft", " ")
m2e.Add "application/vnd.oasis.opendocument.graphics", Split("odg", " ")
m2e.Add "application/vnd.oasis.opendocument.graphics-template", Split("otg", " ")
m2e.Add "application/vnd.oasis.opendocument.image", Split("odi", " ")
m2e.Add "application/vnd.oasis.opendocument.image-template", Split("oti", " ")
m2e.Add "application/vnd.oasis.opendocument.presentation", Split("odp", " ")
m2e.Add "application/vnd.oasis.opendocument.presentation-template", Split("otp", " ")
m2e.Add "application/vnd.oasis.opendocument.spreadsheet", Split("ods", " ")
m2e.Add "application/vnd.oasis.opendocument.spreadsheet-template", Split("ots", " ")
m2e.Add "application/vnd.oasis.opendocument.text", Split("odt", " ")
m2e.Add "application/vnd.oasis.opendocument.text-master", Split("odm", " ")
m2e.Add "application/vnd.oasis.opendocument.text-template", Split("ott", " ")
m2e.Add "application/vnd.oasis.opendocument.text-web", Split("oth", " ")
m2e.Add "application/vnd.olpc-sugar", Split("xo", " ")
m2e.Add "application/vnd.oma.dd2+xml", Split("dd2", " ")
m2e.Add "application/vnd.openofficeorg.extension", Split("oxt", " ")
m2e.Add "application/vnd.openxmlformats-officedocument.presentationml.presentation", Split("pptx", " ")
m2e.Add "application/vnd.openxmlformats-officedocument.presentationml.slide", Split("sldx", " ")
m2e.Add "application/vnd.openxmlformats-officedocument.presentationml.slideshow", Split("ppsx", " ")
m2e.Add "application/vnd.openxmlformats-officedocument.presentationml.template", Split("potx", " ")
m2e.Add "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", Split("xlsx", " ")
m2e.Add "application/vnd.openxmlformats-officedocument.spreadsheetml.template", Split("xltx", " ")
m2e.Add "application/vnd.openxmlformats-officedocument.wordprocessingml.document", Split("docx", " ")
m2e.Add "application/vnd.openxmlformats-officedocument.wordprocessingml.template", Split("dotx", " ")
m2e.Add "application/vnd.osgeo.mapguide.package", Split("mgp", " ")
m2e.Add "application/vnd.osgi.dp", Split("dp", " ")
m2e.Add "application/vnd.osgi.subsystem", Split("esa", " ")
m2e.Add "application/vnd.palm", Split("pdb pqa oprc", " ")
m2e.Add "application/vnd.pawaafile", Split("paw", " ")
m2e.Add "application/vnd.pg.format", Split("str", " ")
m2e.Add "application/vnd.pg.osasli", Split("ei6", " ")
m2e.Add "application/vnd.picsel", Split("efif", " ")
m2e.Add "application/vnd.pmi.widget", Split("wg", " ")
m2e.Add "application/vnd.pocketlearn", Split("plf", " ")
m2e.Add "application/vnd.powerbuilder6", Split("pbd", " ")
m2e.Add "application/vnd.previewsystems.box", Split("box", " ")
m2e.Add "application/vnd.proteus.magazine", Split("mgz", " ")
m2e.Add "application/vnd.publishare-delta-tree", Split("qps", " ")
m2e.Add "application/vnd.pvi.ptid1", Split("ptid", " ")
m2e.Add "application/vnd.quark.quarkxpress", Split("qxd qxt qwd qwt qxl qxb", " ")
m2e.Add "application/vnd.realvnc.bed", Split("bed", " ")
m2e.Add "application/vnd.recordare.musicxml", Split("mxl", " ")
m2e.Add "application/vnd.recordare.musicxml+xml", Split("musicxml", " ")
m2e.Add "application/vnd.rig.cryptonote", Split("cryptonote", " ")
m2e.Add "application/vnd.rim.cod", Split("cod", " ")
m2e.Add "application/vnd.rn-realmedia", Split("rm", " ")
m2e.Add "application/vnd.rn-realmedia-vbr", Split("rmvb", " ")
m2e.Add "application/vnd.route66.link66+xml", Split("link66", " ")
m2e.Add "application/vnd.sailingtracker.track", Split("st", " ")
m2e.Add "application/vnd.seemail", Split("see", " ")
m2e.Add "application/vnd.sema", Split("sema", " ")
m2e.Add "application/vnd.semd", Split("semd", " ")
m2e.Add "application/vnd.semf", Split("semf", " ")
m2e.Add "application/vnd.shana.informed.formdata", Split("ifm", " ")
m2e.Add "application/vnd.shana.informed.formtemplate", Split("itp", " ")
m2e.Add "application/vnd.shana.informed.interchange", Split("iif", " ")
m2e.Add "application/vnd.shana.informed.package", Split("ipk", " ")
m2e.Add "application/vnd.simtech-mindmapper", Split("twd twds", " ")
m2e.Add "application/vnd.smaf", Split("mmf", " ")
m2e.Add "application/vnd.smart.teacher", Split("teacher", " ")
m2e.Add "application/vnd.solent.sdkm+xml", Split("sdkm sdkd", " ")
m2e.Add "application/vnd.spotfire.dxp", Split("dxp", " ")
m2e.Add "application/vnd.spotfire.sfs", Split("sfs", " ")
m2e.Add "application/vnd.stardivision.calc", Split("sdc", " ")
m2e.Add "application/vnd.stardivision.draw", Split("sda", " ")
m2e.Add "application/vnd.stardivision.impress", Split("sdd", " ")
m2e.Add "application/vnd.stardivision.math", Split("smf", " ")
m2e.Add "application/vnd.stardivision.writer", Split("sdw vor", " ")
m2e.Add "application/vnd.stardivision.writer-global", Split("sgl", " ")
m2e.Add "application/vnd.stepmania.package", Split("smzip", " ")
m2e.Add "application/vnd.stepmania.stepchart", Split("sm", " ")
m2e.Add "application/vnd.sun.xml.calc", Split("sxc", " ")
m2e.Add "application/vnd.sun.xml.calc.template", Split("stc", " ")
m2e.Add "application/vnd.sun.xml.draw", Split("sxd", " ")
m2e.Add "application/vnd.sun.xml.draw.template", Split("std", " ")
m2e.Add "application/vnd.sun.xml.impress", Split("sxi", " ")
m2e.Add "application/vnd.sun.xml.impress.template", Split("sti", " ")
m2e.Add "application/vnd.sun.xml.math", Split("sxm", " ")
m2e.Add "application/vnd.sun.xml.writer", Split("sxw", " ")
m2e.Add "application/vnd.sun.xml.writer.global", Split("sxg", " ")
m2e.Add "application/vnd.sun.xml.writer.template", Split("stw", " ")
m2e.Add "application/vnd.sus-calendar", Split("sus susp", " ")
m2e.Add "application/vnd.svd", Split("svd", " ")
m2e.Add "application/vnd.symbian.install", Split("sis sisx", " ")
m2e.Add "application/vnd.syncml+xml", Split("xsm", " ")
m2e.Add "application/vnd.syncml.dm+wbxml", Split("bdm", " ")
m2e.Add "application/vnd.syncml.dm+xml", Split("xdm", " ")
m2e.Add "application/vnd.tao.intent-module-archive", Split("tao", " ")
m2e.Add "application/vnd.tcpdump.pcap", Split("pcap cap dmp", " ")
m2e.Add "application/vnd.tmobile-livetv", Split("tmo", " ")
m2e.Add "application/vnd.trid.tpt", Split("tpt", " ")
m2e.Add "application/vnd.triscape.mxs", Split("mxs", " ")
m2e.Add "application/vnd.trueapp", Split("tra", " ")
m2e.Add "application/vnd.ufdl", Split("ufd ufdl", " ")
m2e.Add "application/vnd.uiq.theme", Split("utz", " ")
m2e.Add "application/vnd.umajin", Split("umj", " ")
m2e.Add "application/vnd.unity", Split("unityweb", " ")
m2e.Add "application/vnd.uoml+xml", Split("uoml", " ")
m2e.Add "application/vnd.vcx", Split("vcx", " ")
m2e.Add "application/vnd.visio", Split("vsd vst vss vsw", " ")
m2e.Add "application/vnd.visionary", Split("vis", " ")
m2e.Add "application/vnd.vsf", Split("vsf", " ")
m2e.Add "application/vnd.wap.wbxml", Split("wbxml", " ")
m2e.Add "application/vnd.wap.wmlc", Split("wmlc", " ")
m2e.Add "application/vnd.wap.wmlscriptc", Split("wmlsc", " ")
m2e.Add "application/vnd.webturbo", Split("wtb", " ")
m2e.Add "application/vnd.wolfram.player", Split("nbp", " ")
m2e.Add "application/vnd.wordperfect", Split("wpd", " ")
m2e.Add "application/vnd.wqd", Split("wqd", " ")
m2e.Add "application/vnd.wt.stf", Split("stf", " ")
m2e.Add "application/vnd.xara", Split("xar", " ")
m2e.Add "application/vnd.xfdl", Split("xfdl", " ")
m2e.Add "application/vnd.yamaha.hv-dic", Split("hvd", " ")
m2e.Add "application/vnd.yamaha.hv-script", Split("hvs", " ")
m2e.Add "application/vnd.yamaha.hv-voice", Split("hvp", " ")
m2e.Add "application/vnd.yamaha.openscoreformat", Split("osf", " ")
m2e.Add "application/vnd.yamaha.openscoreformat.osfpvg+xml", Split("osfpvg", " ")
m2e.Add "application/vnd.yamaha.smaf-audio", Split("saf", " ")
m2e.Add "application/vnd.yamaha.smaf-phrase", Split("spf", " ")
m2e.Add "application/vnd.yellowriver-custom-menu", Split("cmp", " ")
m2e.Add "application/vnd.zul", Split("zir zirz", " ")
m2e.Add "application/vnd.zzazz.deck+xml", Split("zaz", " ")
m2e.Add "application/voicexml+xml", Split("vxml", " ")
m2e.Add "application/widget", Split("wgt", " ")
m2e.Add "application/winhlp", Split("hlp", " ")
m2e.Add "application/wsdl+xml", Split("wsdl", " ")
m2e.Add "application/wspolicy+xml", Split("wspolicy", " ")
m2e.Add "application/x-7z-compressed", Split("7z", " ")
m2e.Add "application/x-abiword", Split("abw", " ")
m2e.Add "application/x-ace-compressed", Split("ace", " ")
m2e.Add "application/x-apple-diskimage", Split("dmg", " ")
m2e.Add "application/x-authorware-bin", Split("aab x32 u32 vox", " ")
m2e.Add "application/x-authorware-map", Split("aam", " ")
m2e.Add "application/x-authorware-seg", Split("aas", " ")
m2e.Add "application/x-bcpio", Split("bcpio", " ")
m2e.Add "application/x-bittorrent", Split("torrent", " ")
m2e.Add "application/x-blorb", Split("blb blorb", " ")
m2e.Add "application/x-bzip", Split("bz", " ")
m2e.Add "application/x-bzip2", Split("bz2 boz", " ")
m2e.Add "application/x-cbr", Split("cbr cba cbt cbz cb7", " ")
m2e.Add "application/x-cdlink", Split("vcd", " ")
m2e.Add "application/x-cfs-compressed", Split("cfs", " ")
m2e.Add "application/x-chat", Split("chat", " ")
m2e.Add "application/x-chess-pgn", Split("pgn", " ")
m2e.Add "application/x-conference", Split("nsc", " ")
m2e.Add "application/x-cpio", Split("cpio", " ")
m2e.Add "application/x-csh", Split("csh", " ")
m2e.Add "application/x-debian-package", Split("deb udeb", " ")
m2e.Add "application/x-dgc-compressed", Split("dgc", " ")
m2e.Add "application/x-director", Split("dir dcr dxr cst cct cxt w3d fgd swa", " ")
m2e.Add "application/x-doom", Split("wad", " ")
m2e.Add "application/x-dtbncx+xml", Split("ncx", " ")
m2e.Add "application/x-dtbook+xml", Split("dtb", " ")
m2e.Add "application/x-dtbresource+xml", Split("res", " ")
m2e.Add "application/x-dvi", Split("dvi", " ")
m2e.Add "application/x-envoy", Split("evy", " ")
m2e.Add "application/x-eva", Split("eva", " ")
m2e.Add "application/x-font-bdf", Split("bdf", " ")
m2e.Add "application/x-font-ghostscript", Split("gsf", " ")
m2e.Add "application/x-font-linux-psf", Split("psf", " ")
m2e.Add "application/x-font-otf", Split("otf", " ")
m2e.Add "application/x-font-pcf", Split("pcf", " ")
m2e.Add "application/x-font-snf", Split("snf", " ")
m2e.Add "application/x-font-ttf", Split("ttf ttc", " ")
m2e.Add "application/x-font-type1", Split("pfa pfb pfm afm", " ")
m2e.Add "application/font-woff", Split("woff", " ")
m2e.Add "application/x-freearc", Split("arc", " ")
m2e.Add "application/x-futuresplash", Split("spl", " ")
m2e.Add "application/x-gca-compressed", Split("gca", " ")
m2e.Add "application/x-glulx", Split("ulx", " ")
m2e.Add "application/x-gnumeric", Split("gnumeric", " ")
m2e.Add "application/x-gramps-xml", Split("gramps", " ")
m2e.Add "application/x-gtar", Split("gtar", " ")
m2e.Add "application/x-hdf", Split("hdf", " ")
m2e.Add "application/x-install-instructions", Split("install", " ")
m2e.Add "application/x-iso9660-image", Split("iso", " ")
m2e.Add "application/x-java-jnlp-file", Split("jnlp", " ")
m2e.Add "application/x-latex", Split("latex", " ")
m2e.Add "application/x-lzh-compressed", Split("lzh lha", " ")
m2e.Add "application/x-mie", Split("mie", " ")
m2e.Add "application/x-mobipocket-ebook", Split("prc mobi", " ")
m2e.Add "application/x-ms-application", Split("application", " ")
m2e.Add "application/x-ms-shortcut", Split("lnk", " ")
m2e.Add "application/x-ms-wmd", Split("wmd", " ")
m2e.Add "application/x-ms-wmz", Split("wmz", " ")
m2e.Add "application/x-ms-xbap", Split("xbap", " ")
m2e.Add "application/x-msaccess", Split("mdb", " ")
m2e.Add "application/x-msbinder", Split("obd", " ")
m2e.Add "application/x-mscardfile", Split("crd", " ")
m2e.Add "application/x-msclip", Split("clp", " ")
m2e.Add "application/x-msdownload", Split("exe dll com bat msi", " ")
m2e.Add "application/x-msmediaview", Split("mvb m13 m14", " ")
m2e.Add "application/x-msmetafile", Split("wmf wmz emf emz", " ")
m2e.Add "application/x-msmoney", Split("mny", " ")
m2e.Add "application/x-mspublisher", Split("pub", " ")
m2e.Add "application/x-msschedule", Split("scd", " ")
m2e.Add "application/x-msterminal", Split("trm", " ")
m2e.Add "application/x-mswrite", Split("wri", " ")
m2e.Add "application/x-netcdf", Split("nc cdf", " ")
m2e.Add "application/x-nzb", Split("nzb", " ")
m2e.Add "application/x-pkcs12", Split("p12 pfx", " ")
m2e.Add "application/x-pkcs7-certificates", Split("p7b spc", " ")
m2e.Add "application/x-pkcs7-certreqresp", Split("p7r", " ")
m2e.Add "application/x-rar-compressed", Split("rar", " ")
m2e.Add "application/x-research-info-systems", Split("ris", " ")
m2e.Add "application/x-sh", Split("sh", " ")
m2e.Add "application/x-shar", Split("shar", " ")
m2e.Add "application/x-shockwave-flash", Split("swf", " ")
m2e.Add "application/x-silverlight-app", Split("xap", " ")
m2e.Add "application/x-sql", Split("sql", " ")
m2e.Add "application/x-stuffit", Split("sit", " ")
m2e.Add "application/x-stuffitx", Split("sitx", " ")
m2e.Add "application/x-subrip", Split("srt", " ")
m2e.Add "application/x-sv4cpio", Split("sv4cpio", " ")
m2e.Add "application/x-sv4crc", Split("sv4crc", " ")
m2e.Add "application/x-t3vm-image", Split("t3", " ")
m2e.Add "application/x-tads", Split("gam", " ")
m2e.Add "application/x-tar", Split("tar", " ")
m2e.Add "application/x-tcl", Split("tcl", " ")
m2e.Add "application/x-tex", Split("tex", " ")
m2e.Add "application/x-tex-tfm", Split("tfm", " ")
m2e.Add "application/x-texinfo", Split("texinfo texi", " ")
m2e.Add "application/x-tgif", Split("obj", " ")
m2e.Add "application/x-ustar", Split("ustar", " ")
m2e.Add "application/x-wais-source", Split("src", " ")
m2e.Add "application/x-x509-ca-cert", Split("der crt", " ")
m2e.Add "application/x-xfig", Split("fig", " ")
m2e.Add "application/x-xliff+xml", Split("xlf", " ")
m2e.Add "application/x-xpinstall", Split("xpi", " ")
m2e.Add "application/x-xz", Split("xz", " ")
m2e.Add "application/x-zmachine", Split("z1 z2 z3 z4 z5 z6 z7 z8", " ")
m2e.Add "application/xaml+xml", Split("xaml", " ")
m2e.Add "application/xcap-diff+xml", Split("xdf", " ")
m2e.Add "application/xenc+xml", Split("xenc", " ")
m2e.Add "application/xhtml+xml", Split("xhtml xht", " ")
m2e.Add "application/xml", Split("xml xsl", " ")
m2e.Add "application/xml-dtd", Split("dtd", " ")
m2e.Add "application/xop+xml", Split("xop", " ")
m2e.Add "application/xproc+xml", Split("xpl", " ")
m2e.Add "application/xslt+xml", Split("xslt", " ")
m2e.Add "application/xspf+xml", Split("xspf", " ")
m2e.Add "application/xv+xml", Split("mxml xhvml xvml xvm", " ")
m2e.Add "application/yang", Split("yang", " ")
m2e.Add "application/yin+xml", Split("yin", " ")
m2e.Add "application/zip", Split("zip", " ")
m2e.Add "audio/adpcm", Split("adp", " ")
m2e.Add "audio/basic", Split("au snd", " ")
m2e.Add "audio/midi", Split("mid midi kar rmi", " ")
m2e.Add "audio/mp4", Split("m4a mp4a", " ")
m2e.Add "audio/mpeg", Split("mpga mp2 mp2a mp3 m2a m3a", " ")
m2e.Add "audio/ogg", Split("oga ogg spx", " ")
m2e.Add "audio/s3m", Split("s3m", " ")
m2e.Add "audio/silk", Split("sil", " ")
m2e.Add "audio/vnd.dece.audio", Split("uva uvva", " ")
m2e.Add "audio/vnd.digital-winds", Split("eol", " ")
m2e.Add "audio/vnd.dra", Split("dra", " ")
m2e.Add "audio/vnd.dts", Split("dts", " ")
m2e.Add "audio/vnd.dts.hd", Split("dtshd", " ")
m2e.Add "audio/vnd.lucent.voice", Split("lvp", " ")
m2e.Add "audio/vnd.ms-playready.media.pya", Split("pya", " ")
m2e.Add "audio/vnd.nuera.ecelp4800", Split("ecelp4800", " ")
m2e.Add "audio/vnd.nuera.ecelp7470", Split("ecelp7470", " ")
m2e.Add "audio/vnd.nuera.ecelp9600", Split("ecelp9600", " ")
m2e.Add "audio/vnd.rip", Split("rip", " ")
m2e.Add "audio/webm", Split("weba", " ")
m2e.Add "audio/x-aac", Split("aac", " ")
m2e.Add "audio/x-aiff", Split("aif aiff aifc", " ")
m2e.Add "audio/x-caf", Split("caf", " ")
m2e.Add "audio/x-flac", Split("flac", " ")
m2e.Add "audio/x-matroska", Split("mka", " ")
m2e.Add "audio/x-mpegurl", Split("m3u", " ")
m2e.Add "audio/x-ms-wax", Split("wax", " ")
m2e.Add "audio/x-ms-wma", Split("wma", " ")
m2e.Add "audio/x-pn-realaudio", Split("ram ra", " ")
m2e.Add "audio/x-pn-realaudio-plugin", Split("rmp", " ")
m2e.Add "audio/x-wav", Split("wav", " ")
m2e.Add "audio/xm", Split("xm", " ")
m2e.Add "chemical/x-cdx", Split("cdx", " ")
m2e.Add "chemical/x-cif", Split("cif", " ")
m2e.Add "chemical/x-cmdf", Split("cmdf", " ")
m2e.Add "chemical/x-cml", Split("cml", " ")
m2e.Add "chemical/x-csml", Split("csml", " ")
m2e.Add "chemical/x-xyz", Split("xyz", " ")
m2e.Add "image/bmp", Split("bmp", " ")
m2e.Add "image/cgm", Split("cgm", " ")
m2e.Add "image/g3fax", Split("g3", " ")
m2e.Add "image/gif", Split("gif", " ")
m2e.Add "image/ief", Split("ief", " ")
m2e.Add "image/jpeg", Split("jpeg jpg jpe", " ")
m2e.Add "image/ktx", Split("ktx", " ")
m2e.Add "image/png", Split("png", " ")
m2e.Add "image/prs.btif", Split("btif", " ")
m2e.Add "image/sgi", Split("sgi", " ")
m2e.Add "image/svg+xml", Split("svg svgz", " ")
m2e.Add "image/tiff", Split("tiff tif", " ")
m2e.Add "image/vnd.adobe.photoshop", Split("psd", " ")
m2e.Add "image/vnd.dece.graphic", Split("uvi uvvi uvg uvvg", " ")
m2e.Add "image/vnd.dvb.subtitle", Split("sub", " ")
m2e.Add "image/vnd.djvu", Split("djvu djv", " ")
m2e.Add "image/vnd.dwg", Split("dwg", " ")
m2e.Add "image/vnd.dxf", Split("dxf", " ")
m2e.Add "image/vnd.fastbidsheet", Split("fbs", " ")
m2e.Add "image/vnd.fpx", Split("fpx", " ")
m2e.Add "image/vnd.fst", Split("fst", " ")
m2e.Add "image/vnd.fujixerox.edmics-mmr", Split("mmr", " ")
m2e.Add "image/vnd.fujixerox.edmics-rlc", Split("rlc", " ")
m2e.Add "image/vnd.ms-modi", Split("mdi", " ")
m2e.Add "image/vnd.ms-photo", Split("wdp", " ")
m2e.Add "image/vnd.net-fpx", Split("npx", " ")
m2e.Add "image/vnd.wap.wbmp", Split("wbmp", " ")
m2e.Add "image/vnd.xiff", Split("xif", " ")
m2e.Add "image/webp", Split("webp", " ")
m2e.Add "image/x-3ds", Split("3ds", " ")
m2e.Add "image/x-cmu-raster", Split("ras", " ")
m2e.Add "image/x-cmx", Split("cmx", " ")
m2e.Add "image/x-freehand", Split("fh fhc fh4 fh5 fh7", " ")
m2e.Add "image/x-icon", Split("ico", " ")
m2e.Add "image/x-mrsid-image", Split("sid", " ")
m2e.Add "image/x-pcx", Split("pcx", " ")
m2e.Add "image/x-pict", Split("pic pct", " ")
m2e.Add "image/x-portable-anymap", Split("pnm", " ")
m2e.Add "image/x-portable-bitmap", Split("pbm", " ")
m2e.Add "image/x-portable-graymap", Split("pgm", " ")
m2e.Add "image/x-portable-pixmap", Split("ppm", " ")
m2e.Add "image/x-rgb", Split("rgb", " ")
m2e.Add "image/x-tga", Split("tga", " ")
m2e.Add "image/x-xbitmap", Split("xbm", " ")
m2e.Add "image/x-xpixmap", Split("xpm", " ")
m2e.Add "image/x-xwindowdump", Split("xwd", " ")
m2e.Add "message/rfc822", Split("eml mime", " ")
m2e.Add "model/iges", Split("igs iges", " ")
m2e.Add "model/mesh", Split("msh mesh silo", " ")
m2e.Add "model/vnd.collada+xml", Split("dae", " ")
m2e.Add "model/vnd.dwf", Split("dwf", " ")
m2e.Add "model/vnd.gdl", Split("gdl", " ")
m2e.Add "model/vnd.gtw", Split("gtw", " ")
m2e.Add "model/vnd.mts", Split("mts", " ")
m2e.Add "model/vnd.vtu", Split("vtu", " ")
m2e.Add "model/vrml", Split("wrl vrml", " ")
m2e.Add "model/x3d+binary", Split("x3db x3dbz", " ")
m2e.Add "model/x3d+vrml", Split("x3dv x3dvz", " ")
m2e.Add "model/x3d+xml", Split("x3d x3dz", " ")
m2e.Add "text/cache-manifest", Split("appcache", " ")
m2e.Add "text/calendar", Split("ics ifb", " ")
m2e.Add "text/css", Split("css", " ")
m2e.Add "text/csv", Split("csv", " ")
m2e.Add "text/html", Split("html htm", " ")
m2e.Add "text/n3", Split("n3", " ")
m2e.Add "text/plain", Split("txt text conf def list log in", " ")
m2e.Add "text/prs.lines.tag", Split("dsc", " ")
m2e.Add "text/richtext", Split("rtx", " ")
m2e.Add "text/sgml", Split("sgml sgm", " ")
m2e.Add "text/tab-separated-values", Split("tsv", " ")
m2e.Add "text/troff", Split("t tr roff man me ms", " ")
m2e.Add "text/turtle", Split("ttl", " ")
m2e.Add "text/uri-list", Split("uri uris urls", " ")
m2e.Add "text/vcard", Split("vcard", " ")
m2e.Add "text/vnd.curl", Split("curl", " ")
m2e.Add "text/vnd.curl.dcurl", Split("dcurl", " ")
m2e.Add "text/vnd.curl.scurl", Split("scurl", " ")
m2e.Add "text/vnd.curl.mcurl", Split("mcurl", " ")
m2e.Add "text/vnd.dvb.subtitle", Split("sub", " ")
m2e.Add "text/vnd.fly", Split("fly", " ")
m2e.Add "text/vnd.fmi.flexstor", Split("flx", " ")
m2e.Add "text/vnd.graphviz", Split("gv", " ")
m2e.Add "text/vnd.in3d.3dml", Split("3dml", " ")
m2e.Add "text/vnd.in3d.spot", Split("spot", " ")
m2e.Add "text/vnd.sun.j2me.app-descriptor", Split("jad", " ")
m2e.Add "text/vnd.wap.wml", Split("wml", " ")
m2e.Add "text/vnd.wap.wmlscript", Split("wmls", " ")
m2e.Add "text/x-asm", Split("s asm", " ")
m2e.Add "text/x-c", Split("c cc cxx cpp h hh dic", " ")
m2e.Add "text/x-fortran", Split("f for f77 f90", " ")
m2e.Add "text/x-java-source", Split("java", " ")
m2e.Add "text/x-opml", Split("opml", " ")
m2e.Add "text/x-pascal", Split("p pas", " ")
m2e.Add "text/x-nfo", Split("nfo", " ")
m2e.Add "text/x-setext", Split("etx", " ")
m2e.Add "text/x-sfv", Split("sfv", " ")
m2e.Add "text/x-uuencode", Split("uu", " ")
m2e.Add "text/x-vcalendar", Split("vcs", " ")
m2e.Add "text/x-vcard", Split("vcf", " ")
m2e.Add "video/3gpp", Split("3gp", " ")
m2e.Add "video/3gpp2", Split("3g2", " ")
m2e.Add "video/h261", Split("h261", " ")
m2e.Add "video/h263", Split("h263", " ")
m2e.Add "video/h264", Split("h264", " ")
m2e.Add "video/jpeg", Split("jpgv", " ")
m2e.Add "video/jpm", Split("jpm jpgm", " ")
m2e.Add "video/mj2", Split("mj2 mjp2", " ")
m2e.Add "video/mp4", Split("mp4 mp4v mpg4", " ")
m2e.Add "video/mpeg", Split("mpeg mpg mpe m1v m2v", " ")
m2e.Add "video/ogg", Split("ogv", " ")
m2e.Add "video/quicktime", Split("qt mov", " ")
m2e.Add "video/vnd.dece.hd", Split("uvh uvvh", " ")
m2e.Add "video/vnd.dece.mobile", Split("uvm uvvm", " ")
m2e.Add "video/vnd.dece.pd", Split("uvp uvvp", " ")
m2e.Add "video/vnd.dece.sd", Split("uvs uvvs", " ")
m2e.Add "video/vnd.dece.video", Split("uvv uvvv", " ")
m2e.Add "video/vnd.dvb.file", Split("dvb", " ")
m2e.Add "video/vnd.fvt", Split("fvt", " ")
m2e.Add "video/vnd.mpegurl", Split("mxu m4u", " ")
m2e.Add "video/vnd.ms-playready.media.pyv", Split("pyv", " ")
m2e.Add "video/vnd.uvvu.mp4", Split("uvu uvvu", " ")
m2e.Add "video/vnd.vivo", Split("viv", " ")
m2e.Add "video/webm", Split("webm", " ")
m2e.Add "video/x-f4v", Split("f4v", " ")
m2e.Add "video/x-fli", Split("fli", " ")
m2e.Add "video/x-flv", Split("flv", " ")
m2e.Add "video/x-m4v", Split("m4v", " ")
m2e.Add "video/x-matroska", Split("mkv mk3d mks", " ")
m2e.Add "video/x-mng", Split("mng", " ")
m2e.Add "video/x-ms-asf", Split("asf asx", " ")
m2e.Add "video/x-ms-vob", Split("vob", " ")
m2e.Add "video/x-ms-wm", Split("wm", " ")
m2e.Add "video/x-ms-wmv", Split("wmv", " ")
m2e.Add "video/x-ms-wmx", Split("wmx", " ")
m2e.Add "video/x-ms-wvx", Split("wvx", " ")
m2e.Add "video/x-msvideo", Split("avi", " ")
m2e.Add "video/x-sgi-movie", Split("movie", " ")
m2e.Add "video/x-smv", Split("smv", " ")
m2e.Add "x-conference/x-cooltalk", Split("ice", " ")